### ISSUE TITLE
Add version getters for common dependencies across products

### ISSUE THREAD

**Issue by ianpittwood** [posit-dev/images-shared#140]
Related to #11

PRs:
- #163 
- #174 
- #193

Similar to #139, we need a way to be able to retrieve an installable dependency version from `bakery` for a variety of use cases.

Uses:
* Retrieval of a dependency version for use in an ephemeral release stream (daily, preview, etc.) build.
* Autofill support for dependency versions during version creation (supports #12).
* Loose dependency pins for future multimatrix build support.

Dependencies we need to support:
* R
* Python
* Quarto
* Pro Drivers

Version pins/calls we should support:
* `latest/stable` - retrieves the latest stable build of the dependency.
* `MAJOR` - retrieves the latest minor/bugfix patch of the dependency.
* `MAJOR.MINOR` - retrieves the latest bugfix patch of the dependency.
* `MAJOR.MINOR.BUGFIX` - retrieves the exact version specified.

We may need to consider the OS involved for the version given based on support restrictions.

---

Summary of the discussion in #49 and where we landed.

We will have two ways to specify dependencies, explicitly, or via a constraint.

```yaml
# Explicit dependency version definition
dependencies:
  - dependency: R
    versions:
      - "4.5.1"
      - "4.4.3"
  - dependency: python
    versions:
      - "3.13.7"
```

```yaml
# Version contstraint definition
dependencies:
  # Install the latest two minor versions of python
  - dependency: python
    versions:
      latest: true
      count: 2
  # Cap the latest version of R at 4.4.x, installing a total of 4 minor versions of R
  - dependency: R
    versions:
      max: "4.4"
      count: 4
  # Install a specific version range, ensuring that the patch version for 1.8 isn't above 16
  # This would help avoid bundling a version where a hypothetical bug was introduced in 1.8.17
  - dependency: quarto
    versions:
      max: "1.8.16"
      min: "1.6"

```
